apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blog-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: blog-db
    spec:
      containers:
      - name: db-container
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        ports:
        - name: db-port
          containerPort: 3306
---

apiVersion: v1
kind: Service
metadata:
  name: blog-db-svc
spec:
  ports:
  - port: 3306
    nodePort: 32001
    targetPort: db-port
    protocol: TCP
  selector:
    app: blog-db
  type: NodePort

